# Generated by Django 2.2.6 on 2019-10-27 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_cargo_grupo'),
        ('estructura', '0001_initial'),
        ('gestion', '0002_auto_20191027_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cargos.Departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='caducidad',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 17, 51, 59, 239260, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Estructura')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Grupo')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member')),
            ],
            options={
                'verbose_name': 'pertenencia a grupo',
                'verbose_name_plural': 'pertenencias a grupo',
            },
        ),
        migrations.CreateModel(
            name='MiembroCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.Cargo')),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Estructura')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member')),
            ],
        ),
    ]
