# Generated by Django 2.2.6 on 2019-10-27 18:06

from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20191027_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='caducidad',
            field=models.DateField(default=gestion.models.return_date_time),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Member'),
        ),
    ]
