# Generated by Django 2.2.6 on 2019-11-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20191028_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['nombre'], 'verbose_name': 'miembro', 'verbose_name_plural': 'miembros'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='in_charge_of',
            new_name='a_cargo_de',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='register',
            new_name='alta',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='sirname',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='drop_out',
            new_name='baja',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='postal_code',
            new_name='codigo_postal',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='department',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='destination',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='study',
            new_name='estudio',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='admission_date',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='birth_date',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='gender',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='city',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='cellphone',
            new_name='movil',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='origin',
            new_name='origen',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='others',
            new_name='otros',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='state',
            new_name='provincia',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='subscription',
            new_name='subscripcion',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='member',
            name='recommended_by',
        ),
        migrations.AddField(
            model_name='member',
            name='recomendado_por',
            field=models.ManyToManyField(blank=True, related_name='_member_recomendado_por_+', to='gestion.Member', verbose_name='recomendado por'),
        ),
    ]
