# Generated by Django 2.2.6 on 2019-11-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20191104_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='omamori_gohonzon',
            field=models.DateField(auto_now=True),
        ),
    ]
