# Generated by Django 2.2.6 on 2019-11-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20191104_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='recomendado_por',
        ),
        migrations.AddField(
            model_name='member',
            name='recomendado_por_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendador_uno', to='gestion.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='recomendado_por_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendador_dos', to='gestion.Member'),
        ),
    ]
