# Generated by Django 2.2.6 on 2019-11-04 22:23

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20191104_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembrocargo',
            options={'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
        migrations.AddField(
            model_name='member',
            name='carta',
            field=models.ImageField(blank=True, upload_to=gestion.models.user_directory_path, verbose_name='carta'),
        ),
        migrations.AddField(
            model_name='miembrogrupo',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miembrogrupo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembrocargo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
