# Generated by Django 2.2.6 on 2019-11-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20191104_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='a_cargo_de',
        ),
        migrations.RemoveField(
            model_name='member',
            name='charge',
        ),
    ]
