# Generated by Django 2.2.6 on 2019-11-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20191106_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiembroCargo',
        ),
    ]
