# Generated by Django 2.2.6 on 2019-11-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20191123_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembrogrupo',
            options={'verbose_name': 'perNonetenencia a grupo', 'verbose_name_plural': 'pertenencias a grupo'},
        ),
        migrations.AddField(
            model_name='member',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='baja',
            field=models.CharField(blank=True, choices=[('Por solicitud', 'Por solicitud'), ('Por traslado a otro país', 'Por traslado a otro país'), ('Por fallecimiento', 'Por fallecimiento'), ('Por razones técnicas', 'Por razones técnicas')], max_length=50, null=True, verbose_name='baja'),
        ),
    ]
