# Generated by Django 2.2.6 on 2019-11-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_auto_20191124_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='recomendacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='comentarios de alta'),
        ),
    ]
