# Generated by Django 2.2.6 on 2019-12-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_auto_20191124_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembrogrupo',
            options={'verbose_name': 'pertenencia a grupo', 'verbose_name_plural': 'pertenencias a grupo'},
        ),
        migrations.RemoveField(
            model_name='miembrogrupo',
            name='estructura',
        ),
    ]
