# Generated by Django 2.2.6 on 2019-12-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_auto_20191206_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='apellidos',
            field=models.CharField(db_index=True, max_length=255, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='fecha_ingreso',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='omamori_gohonzon',
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
