# Generated by Django 2.2.6 on 2019-12-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_auto_20191228_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='omamori_gohonzon',
            new_name='gohonzon',
        ),
        migrations.AddField(
            model_name='member',
            name='gohonzon_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='omamori',
            field=models.BooleanField(default=0),
        ),
    ]
