# Generated by Django 2.2.6 on 2020-01-12 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_auto_20191228_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fecha_estudio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Estudio', verbose_name='estudio'),
        ),
    ]
