# Generated by Django 2.2.6 on 2020-01-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_auto_20200112_0023'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['nombre'], name='gestion_mem_nombre_68d407_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['nombre', 'apellidos'], name='full_index'),
        ),
        migrations.AddIndex(
            model_name='miembrogrupo',
            index=models.Index(fields=['member'], name='gestion_mie_member__338d99_idx'),
        ),
        migrations.AddIndex(
            model_name='miembrogrupo',
            index=models.Index(fields=['member', 'grupo'], name='gestion_mie_member__da98c5_idx'),
        ),
    ]
