# Generated by Django 2.2.6 on 2020-01-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_auto_20200120_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member'),
        ),
    ]
