# Generated by Django 2.2.6 on 2020-01-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_auto_20200127_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='distrito_actual',
        ),
        migrations.RemoveField(
            model_name='member',
            name='distrito_general_actual',
        ),
        migrations.RemoveField(
            model_name='member',
            name='grupo_actual',
        ),
        migrations.RemoveField(
            model_name='member',
            name='grupo_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='region_actual',
        ),
        migrations.RemoveField(
            model_name='member',
            name='zona_actual',
        ),
    ]
