# Generated by Django 2.2.6 on 2020-02-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_auto_20200130_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='teléfono fijo'),
        ),
    ]
