# Generated by Django 2.2.6 on 2020-02-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_auto_20200206_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='omamori',
            new_name='omamori_gohonzon',
        ),
        migrations.AddField(
            model_name='member',
            name='fecha_omamori_gohonzon',
            field=models.DateField(blank=True, null=True),
        ),
    ]
