# Generated by Django 2.2.6 on 2020-02-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_auto_20200206_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fecha_omamori_gohonzon',
        ),
        migrations.RemoveField(
            model_name='member',
            name='omamori_gohonzon',
        ),
        migrations.AddField(
            model_name='member',
            name='omamori_gohonzon',
            field=models.DateField(blank=True, null=True, verbose_name='Omamori Gohonzon'),
        ),
    ]
