# Generated by Django 2.2.6 on 2020-02-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_auto_20200206_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembrogrupo',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
