# Generated by Django 2.2.6 on 2020-02-23 17:15

from django.db import migrations, models
import gestion.models
import gestion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_auto_20200223_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='carta',
            field=models.FileField(blank=True, help_text='El archivo debe tener un tamaño máximo de 2 Mb', null=True, upload_to=gestion.models.user_directory_path, validators=[gestion.validators.ValidateFileSize(2097152)], verbose_name='carta'),
        ),
        migrations.AlterField(
            model_name='member',
            name='foto',
            field=models.ImageField(blank=True, help_text='La imagen debe tener un tamaño máximo de 400 kb', null=True, upload_to=gestion.models.user_directory_path, validators=[gestion.validators.ValidateFileSize(419430)], verbose_name='foto'),
        ),
    ]
