# Generated by Django 2.2.6 on 2020-04-11 16:37

from django.db import migrations, models
import gestion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_auto_20200315_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[gestion.validators.validate_dni], verbose_name='DNI/NIE/PASAPORTE'),
        ),
    ]
