# Generated by Django 2.2.6 on 2020-04-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_auto_20200411_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiembroGrupoCapacitacion',
        ),
    ]
