# Generated by Django 2.2.6 on 2020-04-19 08:17

from django.db import migrations, models
import django.db.models.deletion
import gestion.models
import gestion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0035_delete_miembrogrupocapacitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(db_index=True, help_text='Descripción corta del archivo (max 50 caracteres', max_length=50, verbose_name='descripcion')),
                ('archivo', models.FileField(blank=True, help_text='El archivo debe tener un tamaño máximo de 2 Mb', null=True, upload_to=gestion.models.user_directory_path, validators=[gestion.validators.ValidateFileSize(2097152)], verbose_name='carta')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member')),
            ],
            options={
                'unique_together': {('descripcion', 'member')},
            },
        ),
    ]
