# Generated by Django 2.2.6 on 2020-05-01 12:43

from django.db import migrations, models
import gestion.models
import gestion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0036_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='carta',
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, help_text='El archivo debe tener un tamaño máximo de 2 Mb', null=True, upload_to=gestion.models.document_directory_path, validators=[gestion.validators.ValidateFileSize(2097152)], verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.CharField(db_index=True, help_text='Descripción corta del archivo (max 50 caracteres)', max_length=50, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='member',
            name='alta',
            field=models.CharField(blank=True, choices=[('Ingreso con entrega de Gohonzon', 'Ingreso con entrega de Gohonzon'), ('Ingreso sin entrega de Gohonzon', 'Ingreso sin entrega de Gohonzon'), ('Llegada desde el extranjero', 'Llegada desde el extranjero'), ('Siendo Miembro - entrega o recibir – Gohonzon', 'Siendo Miembro - entrega o recibir - Gohonzon')], max_length=50, null=True, verbose_name='alta'),
        ),
    ]
