# Generated by Django 2.2.6 on 2020-05-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0037_auto_20200501_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='otros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name='member',
            old_name='otros',
            new_name='observaciones',
        ),
    ]
