# Generated by Django 2.2.6 on 2020-05-01 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_auto_20200501_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembrogrupo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
