# Generated by Django 2.2.6 on 2020-05-03 23:42

from django.db import migrations, models
import gestion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_auto_20200501_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[gestion.validators.validate_dni], verbose_name='DNI/NIE/PASAPORTE'),
        ),
    ]
