# Generated by Django 2.2.6 on 2020-05-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_auto_20200503_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=200, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='member',
            name='movil',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='móvil'),
        ),
    ]
