# Generated by Django 2.2.6 on 2020-05-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0041_auto_20200506_2215'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='member',
            name='full_index',
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['nombre', 'apellidos', 'movil', 'email'], name='full_index'),
        ),
    ]
