# Generated by Django 2.2.6 on 2020-05-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_auto_20200506_2217'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='member',
            name='full_index',
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['id', 'nombre', 'apellidos', 'movil', 'email', 'fecha_baja'], name='full_index'),
        ),
    ]
