# Generated by Django 2.2.6 on 2020-05-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0045_auto_20200516_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='recomendacion',
            new_name='observaciones',
        ),
    ]
