# Generated by Django 2.2.6 on 2020-05-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0046_auto_20200516_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
