# Generated by Django 2.2.6 on 2020-05-31 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0047_auto_20200516_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Member'),
        ),
    ]
