# Generated by Django 2.2.14 on 2020-07-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0049_auto_20200723_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='alta',
            field=models.CharField(blank=True, choices=[('Ingreso con entrega de Gohonzon', 'Ingreso con entrega de Gohonzon'), ('Ingreso sin entrega de Gohonzon', 'Ingreso sin entrega de Gohonzon'), ('Llegada desde el extranjero', 'Llegada desde el extranjero'), ('Siendo miembro recibir Gohonzon', 'Siendo miembro recibir Gohonzon')], max_length=50, null=True, verbose_name='alta'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together=set(),
        ),
    ]
