# Generated by Django 2.2.14 on 2020-09-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0050_auto_20200728_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='código postal'),
        ),
    ]
