# Generated by Django 2.2.14 on 2020-10-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0051_auto_20200929_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='omamori_gohonzon',
            new_name='omamori_fecha',
        ),
    ]
