# Generated by Django 2.2.14 on 2020-10-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0052_auto_20201013_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='omamori_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Omamori'),
        ),
    ]
