# Generated by Django 2.2.14 on 2020-10-13 19:29

from django.db import migrations, models


def populate_omamori(apps, schema_editor):
    # We can't import the Member model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Member = apps.get_model('gestion', 'Member')
    for member in Member.objects.all():
        if member.omamori_fecha:
            member.omamori_gohonzon = True
            member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0053_auto_20201013_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='omamori_gohonzon',
            field=models.BooleanField(default=False, verbose_name='Omamori Gohonzon'),
        ),
        migrations.RunPython(populate_omamori),
    ]
