# Generated by Django 2.2.14 on 2020-10-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0054_member_omamori_gohonzon'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fecha_llegada_extranjero',
            field=models.DateField(blank=True, null=True),
        ),
    ]
