# Generated by Django 2.2.14 on 2021-02-28 21:48

from django.db import migrations, models
import gestion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0055_member_fecha_llegada_extranjero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='movil',
            field=models.IntegerField(blank=True, null=True, validators=[gestion.validators.validate_movil], verbose_name='móvil'),
        ),
    ]
