# Generated by Django 2.2.14 on 2021-04-18 08:30

from django.db import migrations, models
import django.db.models.deletion


def copiar_alta_y_baja(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Member = apps.get_model("gestion", "Member")
    AltaMiembro = apps.get_model("gestion", "AltaMiembro")
    BajaMiembro = apps.get_model("gestion", "BajaMiembro")
    members = Member.objects.all()
    for member in members:
        if any((member.alta, member.fecha_ingreso, member.origen, member.fecha_llegada_extranjero)):
            AltaMiembro.objects.create(
                motivo=member.alta,
                fecha=member.fecha_ingreso,
                origen=member.origen,
                fecha_llegada_extranjero=member.fecha_llegada_extranjero,
                member=member
            )
        if any((member.baja, member.fecha_baja, member.destino)):
            BajaMiembro.objects.create(
                motivo=member.baja,
                fecha=member.fecha_baja,
                destino=member.destino,
                member=member
            )


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0056_añade_validación_para_móvil'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaMiembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('destino', models.CharField(blank=True, max_length=50, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member')),
            ],
            options={
                'verbose_name': 'baja',
                'verbose_name_plural': 'bajas',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='AltaMiembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name = "Fecha ingreso SG")),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('origen', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_llegada_extranjero', models.DateField(blank=True, null=True, verbose_name = "Fecha incorporación SGEs")),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member')),
            ],
            options={
                'verbose_name': 'alta',
                'verbose_name_plural': 'altas',
                'ordering': ['fecha'],
            },
        ),
        migrations.RunPython(copiar_alta_y_baja),
    ]
