# Generated by Django 2.2.14 on 2021-04-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0057_altamiembro_bajamiembro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fecha_llegada_extranjero',
        ),
        migrations.RemoveField(
            model_name='member',
            name='origen',
        ),
    ]
