# Generated by Django 2.2.14 on 2021-04-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0058_auto_20210418_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altamiembro',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Ingreso con entrega de Gohonzon', 'Ingreso con entrega de Gohonzon'), ('Ingreso sin entrega de Gohonzon', 'Ingreso sin entrega de Gohonzon'), ('Llegada desde el extranjero', 'Llegada desde el extranjero'), ('Siendo miembro recibir Gohonzon', 'Siendo miembro recibir Gohonzon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bajamiembro',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Por solicitud', 'Por solicitud'), ('Por traslado a otro país', 'Por traslado a otro país'), ('Por fallecimiento', 'Por fallecimiento'), ('Por razones técnicas', 'Por razones técnicas')], max_length=50, null=True),
        ),
    ]
