# Generated by Django 2.2.14 on 2021-05-23 15:30

from django.db import migrations, models
import django.db.models.deletion


def copiar_departamento_actual(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Member = apps.get_model("gestion", "Member")
    MiembroDepartamento = apps.get_model("gestion", "MiembroDepartamento")
    members = Member.objects.filter(departamento__isnull=False).all()
    for member in members:
        MiembroDepartamento.objects.create(
            member=member,
            departamento=member.departamento
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0038_rangocapacitacion_asignable_rer'),
        ('gestion', '0061_hace_nombre_y_apellidos_opcionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.Departamento')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member')),
            ],
            options={
                'verbose_name': 'pertenencia a departamento',
                'verbose_name_plural': 'pertenencias a departamento',
            },
        ),
        migrations.AddIndex(
            model_name='miembrodepartamento',
            index=models.Index(fields=['member'], name='gestion_mie_member__7c66a3_idx'),
        ),
        migrations.AddIndex(
            model_name='miembrodepartamento',
            index=models.Index(fields=['member', 'departamento'], name='gestion_mie_member__b999d5_idx'),
        ),
        migrations.RunPython(copiar_departamento_actual),
    ]
