# Generated by Django 2.2.24 on 2021-09-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0062_miembro_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='fecha ingreso SG'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gohonzon',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Gohonzon'),
        ),
    ]
