# Generated by Django 2.2.6 on 2019-10-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DistritoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'distrito general',
                'verbose_name_plural': 'distritos generales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'región',
                'verbose_name_plural': 'regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Region')),
            ],
            options={
                'verbose_name': 'zona general',
                'verbose_name_plural': 'zonas generales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('zona_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.ZonaGeneral')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Distrito')),
                ('distrito_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.DistritoGeneral')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Grupo')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Region')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Zona')),
                ('zona_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.ZonaGeneral')),
            ],
        ),
        migrations.AddField(
            model_name='distritogeneral',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Zona'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='distrito_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.DistritoGeneral'),
        ),
    ]
