# Generated by Django 2.2.6 on 2020-01-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0004_delete_estructura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='distrito'),
        ),
        migrations.AlterField(
            model_name='distritogeneral',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='distrito general'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='región'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='zona'),
        ),
        migrations.AddIndex(
            model_name='distrito',
            index=models.Index(fields=['nombre'], name='estructura__nombre_d68f38_idx'),
        ),
        migrations.AddIndex(
            model_name='distrito',
            index=models.Index(fields=['nombre', 'distrito_general'], name='estructura__nombre_d223e9_idx'),
        ),
        migrations.AddIndex(
            model_name='distritogeneral',
            index=models.Index(fields=['nombre'], name='estructura__nombre_ed0784_idx'),
        ),
        migrations.AddIndex(
            model_name='distritogeneral',
            index=models.Index(fields=['nombre', 'zona'], name='estructura__nombre_10e76b_idx'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['nombre'], name='estructura__nombre_62dd22_idx'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['nombre', 'distrito'], name='estructura__nombre_5df9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='zona',
            index=models.Index(fields=['nombre'], name='estructura__nombre_282623_idx'),
        ),
        migrations.AddIndex(
            model_name='zona',
            index=models.Index(fields=['nombre', 'region'], name='estructura__nombre_af344d_idx'),
        ),
    ]
