# Generated by Django 2.2.6 on 2020-03-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0029_auto_20200303_2242'),
        ('estructura', '0007_auto_20200315_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEstructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.Nivel')),
            ],
        ),
    ]
