# Generated by Django 2.2.6 on 2020-03-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0008_historicoestructura'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoestructura',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
