# Generated by Django 2.2.14 on 2020-09-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0011_auto_20200315_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distritogeneral',
            options={'ordering': ['nombre'], 'verbose_name': 'Distrito General', 'verbose_name_plural': 'Distritos Generales'},
        ),
    ]
