# Generated by Django 2.2.6 on 2019-10-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estructura.Grupo'),
            preserve_default=False,
        ),
    ]
