# Generated by Django 2.2.6 on 2019-10-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_cargo_grupo'),
        ('gestion', '0003_auto_20191027_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='miembros',
            field=models.ManyToManyField(through='gestion.MiembroCargo', to='gestion.Member'),
        ),
    ]
