# Generated by Django 2.2.6 on 2019-11-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0003_cargo_miembros'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='codigo',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rango',
            name='codigo',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
