# Generated by Django 2.2.6 on 2019-11-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0004_auto_20191106_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rango',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
