# Generated by Django 2.2.6 on 2019-11-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20191106_1027'),
        ('cargos', '0005_auto_20191110_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='miembros',
        ),
        migrations.AddField(
            model_name='cargo',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Member'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.Departamento'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.Nivel'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='rango',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.Rango'),
        ),
    ]
