# Generated by Django 2.2.6 on 2019-11-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0006_auto_20191110_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
    ]
