# Generated by Django 2.2.6 on 2019-11-10 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0008_auto_20191110_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
