# Generated by Django 2.2.6 on 2019-11-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0009_cargo_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='miembro',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='rango',
        ),
    ]
