# Generated by Django 2.2.6 on 2019-11-10 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_delete_miembrocargo'),
        ('cargos', '0010_auto_20191110_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.Departamento'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Member'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.Nivel'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='rango',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.Rango'),
        ),
    ]
