# Generated by Django 2.2.6 on 2019-11-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0012_cargo_foreignkey_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='foreignkey_id',
            new_name='object_id',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
