# Generated by Django 2.2.6 on 2019-11-10 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0014_auto_20191110_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nivel',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'estructura'), ('model', 'region')), models.Q(('app_label', 'estructura'), ('model', 'distrito')), models.Q(('app_label', 'estructura'), ('model', 'zona')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
