# Generated by Django 2.2.6 on 2019-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0015_auto_20191110_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
