# Generated by Django 2.2.6 on 2019-11-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0017_auto_20191110_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rango',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
