# Generated by Django 2.2.6 on 2019-11-11 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0018_auto_20191110_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='nivel',
            new_name='content_type',
        ),
    ]
