# Generated by Django 2.2.6 on 2019-11-16 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_delete_miembrocargo'),
        ('cargos', '0021_auto_20191111_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='content_type',
        ),
        migrations.AddField(
            model_name='cargo',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cargos.Nivel'),
            preserve_default=False,
        ),
    ]
