# Generated by Django 2.2.6 on 2019-11-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0022_auto_20191116_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member', verbose_name='miembro'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
