# Generated by Django 2.2.6 on 2020-02-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cargos', '0023_auto_20191124_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='nivel',
        ),
        migrations.AddField(
            model_name='cargo',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
