# Generated by Django 2.2.6 on 2020-02-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0025_auto_20200206_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
