# Generated by Django 2.2.6 on 2020-02-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0026_auto_20200212_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rango',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
