# Generated by Django 2.2.6 on 2020-03-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0027_auto_20200213_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'grupo de capacitación',
                'verbose_name_plural': 'grupos de capacitación',
                'ordering': ['nombre'],
            },
        ),
    ]
