# Generated by Django 2.2.6 on 2020-03-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0028_grupocapacitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='fecha_baja',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='grupocapacitacion',
            name='fecha_baja',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='fecha_baja',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='rango',
            name='fecha_baja',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
