# Generated by Django 2.2.6 on 2020-04-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0035_delete_miembrogrupocapacitacion'),
        ('cargos', '0029_auto_20200303_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.Departamento')),
                ('grupo_capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.GrupoCapacitacion')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member', verbose_name='miembro')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.Nivel')),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.Rango')),
            ],
            options={
                'verbose_name': 'cargo de capacitación',
                'verbose_name_plural': 'cargos de capacitación',
            },
        ),
    ]
