# Generated by Django 2.2.6 on 2020-05-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0031_auto_20200418_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargocapacitacion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
