# Generated by Django 2.2.6 on 2020-05-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0032_auto_20200503_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='rango',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
