# Generated by Django 2.2.14 on 2020-10-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0033_rango_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
