# Generated by Django 2.2.14 on 2021-02-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0035_nivel_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='asignable_RER',
            field=models.BooleanField(default=False, verbose_name='asignable por RER'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='asignable_REZ',
            field=models.BooleanField(default=False, verbose_name='asignable por REZ'),
        ),
    ]
